version: '3'

services:
  php:
    build:
      context: ./www
      args:
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: ./database
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
