version: '3'

services:
  php:
    build:
      context: ./www
      args:
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    build:
      context: ./database
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
